const mongoose = require("mongoose");

const gameSchema = new mongoose.Schema(
  {
    title: { type: String, required: true, unique: true, trim: true },
    imageUrl: { type: String, required: true },
    developer: { type: String, required: true, trim: true },
    publisher: { type: String, required: true, trim: true },
    releaseDate: { type: String, required: true },
    tags: {
      type: [String],
      default: [],
      enum: [
        "Action",
        "Adventure",
        "RPG",
        "MMORPG",
        "FPS",
        "Strategy",
        "Puzzle",
        "Simulation",
        "Sports",
        "Racing",
        "Fighting",
        "Stealth",
        "Survival",
        "Horror",
        "Platformer",
        "Point-and-Click",
        "Visual Novel",
        "Interactive Fiction",
        "Hack and Slash",
        "Beat 'em up",
        "Shooter",
        "Tower Defense",
        "MOBA",
        "Battle Royale",
        "Sandbox",
        "Open World",
        "Card Game",
        "Board Game",
        "Educational",
        "Music",
        "Rhythm",
        "Party",
        "Arcade",
        "VR",
        "Co-op",
        "Multiplayer",
        "Singleplayer",
        "Online Multiplayer",
        "Local Multiplayer",
        "PvE",
        "PvP",
        "Turn-Based",
        "Real-Time",
        "2D",
        "3D",
        "Text-Based",
        "Retro",
        "Indie",
        "Casual",
        "Hardcore",
        "Narrative",
        "First-Person",
        "Third-Person",
        "Top-Down",
        "Side-Scroller",
        "Isometric",
        "Tactical",
        "Roguelike",
        "Roguelite",
        "Dungeon Crawler",
        "Crafting",
        "Building",
        "Exploration",
        "Physics",
        "Procedural Generation",
        "Early Access",
        "VR Supported",
        "eSports",
        "Family-Friendly",
        "Fantasy",
        "Sci-Fi",
        "Historical",
        "War",
        "Steampunk",
        "Cyberpunk",
        "Post-Apocalyptic",
        "Space",
        "Zombies",
        "Superhero",
        "Anime",
        "Mystery",
        "Thriller",
      ],
    },
    createdBy: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
    reviews: {
      type: [mongoose.Schema.Types.ObjectId],
      ref: "Review",
      default: [],
    },
    reviewScore: { type: Number, default: 0 },
    price: { type: Number, required: true },
    discountInPercent: { type: Number, default: 0 },
    currency: { type: String, default: "EUR" },
    description: { type: String, required: true, trim: true },
    ageRestricted: { type: Boolean, default: false },
  },
  { timestamps: true }
);

const Game = mongoose.model("Game", gameSchema);

module.exports = Game;
